spring.application.name=vc-wallet
server.port=8082
wallet.base-url=http://localhost:${server.port}
wallet.issuer-url=http://localhost:8080
wallet.verifier-url=http://localhost:8081
management.endpoints.web.exposure.include=health,info
