spring:
  application:
    name: issuer
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

logging:
  level:
    org.springframework.security: trace
server:
  port: 9091