spring.application.name=vc-verifier
server.port=8081
verifier.base-url=http://localhost:${server.port}
verifier.issuer-url=http://localhost:8080
verifier.issuer-jwks-uri=${verifier.issuer-url}/jwks
management.endpoints.web.exposure.include=health,info
